# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.srcs/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/myBlock2_axi_smc_0.xci
# IP: The module: 'myBlock2_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/bd_3e6c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_0/bd_3e6c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_1/bd_3e6c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_2/bd_3e6c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_3/bd_3e6c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_4/bd_3e6c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_5/bd_3e6c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_6/bd_3e6c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_7/bd_3e6c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_8/bd_3e6c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_9/bd_3e6c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_1/bd_3e6c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_1/bd_3e6c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_5/bd_3e6c_s00a2s_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_6/bd_3e6c_sarn_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_6/bd_3e6c_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_7/bd_3e6c_srn_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_7/bd_3e6c_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_8/bd_3e6c_m00s2a_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock2_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock2_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.srcs/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/myBlock2_axi_smc_0.xci
# IP: The module: 'myBlock2_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/bd_3e6c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_0/bd_3e6c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_1/bd_3e6c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_2/bd_3e6c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_3/bd_3e6c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_4/bd_3e6c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_5/bd_3e6c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_6/bd_3e6c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_7/bd_3e6c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_8/bd_3e6c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_9/bd_3e6c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_1/bd_3e6c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_1/bd_3e6c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_5/bd_3e6c_s00a2s_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_6/bd_3e6c_sarn_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_6/bd_3e6c_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_7/bd_3e6c_srn_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_7/bd_3e6c_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/bd_0/ip/ip_8/bd_3e6c_m00s2a_0_ooc.xdc

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock2_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock2_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
