# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_xbar_0/imageProcessingSystem_xbar_0.xci
# IP: The module: 'imageProcessingSystem_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.gen/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_xbar_0/imageProcessingSystem_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_xbar_0/imageProcessingSystem_xbar_0.xci
# IP: The module: 'imageProcessingSystem_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.gen/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_xbar_0/imageProcessingSystem_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessingSystem_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
