# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcess_0_0/imageProcessingSystem_imageProcess_0_0.xci
# IP: The module: 'imageProcessingSystem_imageProcess_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.gen/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcess_0_0/src/outputBuffer/outputBuffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.gen/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcess_0_0/src/outputBuffer/outputBuffer.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.srcs/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcess_0_0/imageProcessingSystem_imageProcess_0_0.xci
# IP: The module: 'imageProcessingSystem_imageProcess_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.gen/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcess_0_0/src/outputBuffer/outputBuffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: c:/Users/hp/Desktop/imageProcessingSystem/imageProcessingSystem.gen/sources_1/bd/imageProcessingSystem/ip/imageProcessingSystem_imageProcess_0_0/src/outputBuffer/outputBuffer.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
