# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.srcs/sources_1/bd/myBlock2/ip/myBlock2_auto_pc_0/myBlock2_auto_pc_0.xci
# IP: The module: 'myBlock2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_auto_pc_0/myBlock2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.srcs/sources_1/bd/myBlock2/ip/myBlock2_auto_pc_0/myBlock2_auto_pc_0.xci
# IP: The module: 'myBlock2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Desktop/NeuralNetwork2/Tut-8/myProject1/myProject1.gen/sources_1/bd/myBlock2/ip/myBlock2_auto_pc_0/myBlock2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
